#!/bin/bash

SDK=/Users/prife/Library/Android/sdk/sources/android-25

function get_abs_path() {
    readlink -f $1
}

SELF_PATH=$(dirname $(get_abs_path $(which $0)))

function dump_intent_flag() {
    sed -n 's/[ ]*public static final int \(FLAG_[^ ]*\) = \(0[xX][^;]*\);/\2:Intent.\1/p' ${SDK}/android/content/Intent.java > intent_flag.txt
    echo "warning: now please fix $SELF_PATH/intent_flag.txt by hand, there duplicated flags!"
}

function dump_context_service() {
    sed -n 's/[\t ]*public static final String \([^ ]*\) = "\([a-zA-Z_]*\)";/"\2":Context.\1/p' ${SDK}/android/content/Context.java > context_service.txt
}

function dump_intent_action() {
    sed -n 's/[\t ]*public static final String \([^ ]*\) = "\(android.intent.[^"]*\)";/"\2":Intent.\1/p' ${SDK}/android/content/Intent.java > intent_action.txt
}

function dump_window_lp_flag() {
    sed -n 's/ *public static final int \(FLAG_[^ ]*\) *= *\(0[xX][^;]*\);/\2:WindowManager.LayoutParams.\1/p' ${SDK}/android/view/WindowManager.java > window_lp_flag.txt
}

#-- main --
if [ x"$1" == x -o ! -d "$1" -o ! -f "$1"/android/content/Intent.java ]; then
    echo "warning, SDK path [$SDK] is not valid!"
    exit 1
fi

SDK=$1

cd $SELF_PATH

dump_intent_flag
dump_intent_action
dump_context_service
dump_window_lp_flag
