#!/bin/bash

function get_abs_path() {
    readlink -f $1 
}

function get_files() {
    local name=$1
    local dir=$2
    find ${dir} -name "${name}.*"
}

function replace_cp() {
    local src_dir=$1
    local des_dir=$(get_abs_path $2)
    local HERE=$(pwd)
    cd $src_dir
    file_list=(`find . -type f`)
    for i in ${file_list[*]}; do
        local filename=$(basename ${i%.*})
        local todir=$(dirname $des_dir/$i)
        local override_files=$(get_files $filename $todir)
        echo "$1/$i -> $2/$i"
        for k in ${override_files[*]}; do
            echo " $k"
            rm "$k"
        done
        cp $i $des_dir/$i
    done
    cd $HERE
}

replace_cp $@

